name: Bulid LaTeX
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Notes
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            notes/notes.tex
            slides/slides.tex
